name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23', '1.22']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download dependencies
        run: go mod tidy

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -v ./...

      - name: Install
        run: go install ./cmd/chip8
